# Generated by Django 3.2.22 on 2024-03-12 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dugcwv1mf/image/upload/v1710255259/Project%201/Screenshot_2024-03-12_at_2.53.56_PM_sjwbld.png', max_length=255, verbose_name='image'),
        ),
    ]
